### ISSUE TITLE
lore outputting erroneous audio when rendering

### ISSUE THREAD

**Issue by ListeningGarden** [micah-frank-studio/Lore#15]
when attempting to render audio through lore as a vst, lore outputs extremely harsh and dangerously painful noise at maximum amplitude instead of the audio output expected. even though i have turned down the volume for this video, please be mindful of your volume level before listening

https://user-images.githubusercontent.com/36242661/232114335-745b0cfb-015f-4fe4-905f-de465b0947b7.mp4

i am exporting through bitwig studio on windows 10, should this help narrow down where the issue may be

**Comment by ListeningGarden** [comment]
i have also updated my cabbage build to the most recent nightly available for windows, though @rorywalsh may need to investigate as the artifacts have not produced a windows build for the past 4 builds

**Comment by micah-frank-studio** [comment]
And this is in the rendered file, correct? Not in Bitwig's output?

**Comment by ListeningGarden** [comment]
correct, lore itself functions perfectly well when working live through the daw and i can hear the expected output then. it only seems to happen when rendering a file through bitwig's export prompt, at least that i've noticed so far in my brief afternoon of testing

**Comment by micah-frank-studio** [comment]
I opened it in Reaper on windows and got a sound similar to what is in your file. I cannot seem to reproduce it in anything else or on OSX. I also cannot reproduce it in Reaper again. My rendered files seem fine too. I'll test some more and see what I can find. Let me know if you can consistently reproduce it. My apologies and please watch your speakers and ears.... hopefully I can pinpoint the issue quickly

**Comment by micah-frank-studio** [comment]
@ListeningGarden do you know if this was a new instance of Lore? Or was it an instance you recalled from a previous session? I am wondering if the issue happens on recall or when one upgrades from one version and reloads the session.

**Comment by ListeningGarden** [comment]
@micah-frank-studio this was 100% a new instance, i added it to a track that i had started earlier in the week and i haven't loaded lore into it previously

**Comment by micah-frank-studio** [comment]
@ListeningGarden try the latest. I just pushed a fix that might have caused the issue — the spectral freeze selection wasn't setting properly to its default value... maybe that will fix it! 🤞

**Comment by ListeningGarden** [comment]
@micah-frank-studio unfortunately the spectral freeze bug did not resolve the rendering issue, but a good catch nonetheless!

**Comment by rorywalsh** [comment]
I'm late to the party here, but is there any chance you are rendering at a different sample rate to the session? @ListeningGarden, apologise for not spotting the fault with the Windows build, I'm looking into it now. Should have it sorted shortly. Thanks for letting me know :)

**Comment by ListeningGarden** [comment]
@rorywalsh everything across the board is set to 48000khz that i can see. the issue must have cropped up at some point since lore and/or cabbage releases dated past december or january, as the only recordings i have which lore was in place for during exporting exist before then and did not exhibit this issue. in case this helps narrow things down a little.

**Comment by rorywalsh** [comment]
Thanks @ListeningGarden A lot of code has passed under the bridge since December. I'll have to test it myself to see. Might take some time, but I'll let you know if I can spot the issue.
